In [9]:
 #default values

In [60]:
import pickle
with open('model.pkl', 'rb') as file:
    model = pickle.load(file)

import pandas as pd
import numpy as np

height,slope,rainfall = 100.000000,26.276745,100.051028 #default values its input

test = {
    'height': [height],
    'slope': [slope],
    'rainfall': [rainfall]
}

test = pd.DataFrame(test)
test.head()

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


height      slope    rainfall
0   100.0  26.276745  100.051028

In [61]:
y_pred=model.predict(test)

In [62]:
y_pred

array([1], dtype=int64)

In [63]:
if y_pred[0] == 0:
    print("no landslide risks")
else:
    print("found landslide risks")

found landslide risks


In [66]:
y_pred_proba = model.predict_proba(test)

Probabilities in percentage:
 [[  0. 100.]]


In [67]:
y_pred_percent = np.round(model.predict_proba(test) * 100, 1)
print(y_pred_percent)

[[  0. 100.]]
